### ISSUE TITLE
Fullscreen & Sessions corrupting tabline

### ISSUE THREAD

**Issue by mMontu** [xolox/vim-shell#11] opened 2013-05-22 19:24 UTC
When a session is save the full screen mode is persisted. But after reloading the session, exiting fullscreen shows a tabline that is corrupted. Entering and exiting fullscreen mode doesn't restores the tabline to its normal graphics.

**Comment by xolox** [comment] 2013-05-23 00:01
Are you saying the tab line options should be persisted and restored between sessions, or are you saying the interaction between the fullscreen & session functionalities causes actual display corruption, as in visual artefacts that don't make sense?

**Comment by mMontu** [comment] 2013-05-23 11:51
The second option, display corruption:
![tabline corruption](https://f.cloud.github.com/assets/1397534/554110/0232a250-c39f-11e2-890b-a4546e0c1310.png)

Contents of _vimrc:

```
set nocompatible
filetype plugin on
syntax on 
```

**Comment by xolox** [comment] 2013-05-23 17:06
Okay, the main menu and the graphical tabs disappeared. Thanks for the screenshots, they help disambiguate what's going on. It's not really corruption but I can see how it would appear like corruption if you don't know that this is a feature of Vim (text mode tab lines).

Anyway, it seems like the interaction of my plug-ins somehow clears the value of [guioptions](http://vimdoc.sourceforge.net/htmldoc/options.html#'guioptions'). I'll take a look this weekend (_very_ busy week at work :-). If you're very much attached to the plug-ins in the mean time, you can downgrade to the previous release. Sorry for breaking things :-s.

**Comment by xolox** [comment] 2013-05-23 23:32
I can't reproduce this so far... I use (mainly test) both the shell and session plug-ins on Windows XP and the interaction works fine for me. When you restart Vim, does it open in fullscreen mode or not? Right after Vim starts, can you execute `:set go?` and report the output here?

**Comment by mMontu** [comment] 2013-05-24 11:48
Sorry for the confusion, I indeed wasn't aware of text mode tab lines. I understand that you are busy, please don't feel like I'm pushing you -- your plugins are great, I'm only trying to help improving then :).

I'm performing the tests in Windows XP, with latest gVim from [vim.org](http://www.vim.org/download.php#pc). I wonder why it only happens here.

After restart it open in fullscreen -- the problem is noticed only after restart and exiting fullscreen.

Opening gVim without loading session: `guioptions=egmrLtT`.
After restart: `guioptions=grLt` (doesn't change when exits fullscreen).
`set go+=e` indeed restores tablines to its default appeareance.

You are right about the problem with `guioptions`: after issuing `SaveSession` without fullscreen the `~/vimfiles/sessions/default.vim` contains `set guioptions=egmrLtT` if . With fullscreen active, the default session contains `set guioptions=grLt`.

Please let me know if there are any other tests that I can perform.

**Comment by xolox** [comment] 2013-05-25 13:40
Thanks for the details, it took me a while but I can reproduce it now, this is definitely a bug.

**Comment by xolox** [comment] 2013-05-25 17:10
Please try the latest versions of the vim-shell and vim-session plug-ins. Both have been updated and with the latest versions this issue should be resolved. I'm closing this issue now, but if the problem persists feel free to reopen the issue. Thanks for the bug report!

---

I'm not sure how you install Vim plug-ins, but mind the following gotcha (a very recent change):

[From the readme](https://github.com/xolox/vim-shell#installation):

> _Please note that the vim-shell plug-in requires my vim-misc plug-in which is separately distributed._

[From the vim-misc readme](https://github.com/xolox/vim-misc#miscellaneous-auto-load-vim-scripts):

> The vim-misc plug-in contains Vim scripts that are used by most of the Vim plug-ins I've written yet don't really belong with any single one of the plug-ins. Basically it's an extended standard library of Vim script functions that I wrote during the development of my Vim profile and plug-ins.
> 
> **In the past these scripts were bundled with each plug-in, however that turned out to be a maintenance nightmare for me. That's why the miscellaneous scripts are now a proper plug-in with their own page on Vim Online.**
> 
> **Because the miscellaneous scripts are no longer bundled with my Vim plug-ins, users are now required to install the miscellaneous scripts separately**. This is unfortunate for users who are upgrading from a previous release that did bundle the miscellaneous scripts, but I don't see any way around this. Sorry!

**Closed as completed by xolox** 2013-05-25 17:10 UTC

**Comment by mMontu** [comment] 2013-05-25 18:27
I'm unable to test it until Monday, because I don't have my settings/plugins here. I use pathogen to manage my plugins - thanks for your reminder!

**Comment by mMontu** [comment] 2013-05-27 20:27
It works like a charm! Thank you very much!
